# Generated by Django 5.2 on 2026-10-07 20:44

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1920, 1440], upload_to='gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('lift_type', models.CharField(choices=[('gondola', 'Гондольный'), ('chair', 'Кресельный'), ('drag', 'Бугельный'), ('carpet', 'Траволатор')], max_length=10, verbose_name='Тип')),
                ('length_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина, м')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пропускная способность, чел/ч')),
                ('hours', models.CharField(blank=True, max_length=60, verbose_name='Часы работы')),
                ('is_open', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Подъёмник',
                'verbose_name_plural': 'Подъёмники',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Раздел меню',
                'verbose_name_plural': 'Меню: разделы',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1600, 1200], upload_to='offers/', verbose_name='Изображение')),
                ('label', models.CharField(blank=True, help_text='Например: −20%', max_length=60, verbose_name='Плашка')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Спецпредложение',
                'verbose_name_plural': 'Спецпредложения',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1600, 1200], upload_to='blog/', verbose_name='Изображение')),
                ('excerpt', models.TextField(blank=True, verbose_name='Анонс')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Блог',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1600, 1200], upload_to='rooms/covers/', verbose_name='Изображение')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('max_guests', models.PositiveSmallIntegerField(default=2, verbose_name='Гостей, до')),
                ('beds', models.CharField(blank=True, max_length=120, verbose_name='Кровати')),
                ('area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Площадь, м²')),
                ('price_from', models.PositiveIntegerField(verbose_name='Цена от, сом / ночь')),
                ('amenities', models.TextField(blank=True, help_text='Каждая строка — отдельный пункт', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера и жильё',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1600, 1200], upload_to='services/covers/', verbose_name='Изображение')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkiPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, сом')),
                ('price_child', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена для детей, сом')),
                ('features', models.TextField(blank=True, help_text='Каждая строка — отдельный пункт', verbose_name='Что входит')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Выделить')),
            ],
            options={
                'verbose_name': 'Ски-пасс',
                'verbose_name_plural': 'Ски-пассы',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('level', models.CharField(choices=[('green', 'Зелёная'), ('blue', 'Синяя'), ('red', 'Красная'), ('black', 'Чёрная')], max_length=10, verbose_name='Сложность')),
                ('length_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина, м')),
                ('vertical_drop_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Перепад высот, м')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыта')),
            ],
            options={
                'verbose_name': 'Трасса',
                'verbose_name_plural': 'Трассы',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(help_text='Например: Бишкек → курорт', max_length=120, verbose_name='Маршрут')),
                ('departure_point', models.CharField(blank=True, max_length=255, verbose_name='Место отправления')),
                ('schedule', models.CharField(blank=True, help_text='Например: сб и вс в 7:00', max_length=255, verbose_name='Расписание')),
                ('duration', models.CharField(blank=True, help_text='Например: ~2,5 часа', max_length=60, verbose_name='В пути')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена, сом')),
                ('price_unit', models.CharField(blank=True, default='место', max_length=60, verbose_name='Цена за')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Маршрут трансфера',
                'verbose_name_plural': 'Трансфер',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Состав / описание')),
                ('weight', models.CharField(blank=True, help_text='Например: 250 г, 0,5 л', max_length=40, verbose_name='Выход')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, сом')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='menu/', verbose_name='Изображение')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хит')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menucategory', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Меню: блюда',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1600, 1200], upload_to='rooms/gallery/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Фото номера',
                'verbose_name_plural': 'Фото номера',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1600, 1200], upload_to='services/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.CharField(blank=True, help_text='Например: от 1 500 сом / час', max_length=120, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cms.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
