# Generated by Django 5.2 on 2026-10-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferroute',
            name='name',
            field=models.CharField(help_text='Например: Бишкек → Baytur', max_length=120, verbose_name='Маршрут'),
        ),
    ]
