# Generated by Django 5.2 on 2026-10-07 21:48

import apps.base.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('icon', models.CharField(blank=True, choices=[('mountain', 'Гора'), ('snow', 'Снежинка'), ('lift', 'Подъёмник'), ('sun', 'Солнце'), ('ski', 'Лыжи'), ('home', 'Домик'), ('food', 'Еда'), ('car', 'Трансфер')], max_length=20, verbose_name='Иконка')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', apps.base.models.RichTextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[2400, 1350], upload_to='home/slides/', verbose_name='Изображение')),
                ('eyebrow', models.CharField(blank=True, max_length=120, verbose_name='Надзаголовок')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Слайд на главной',
                'verbose_name_plural': 'Слайды на главной',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Страница со slug «about» выводится в разделе «О курорте»', unique=True, verbose_name='URL')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1600, 1200], upload_to='pages/', verbose_name='Изображение')),
                ('content', apps.base.models.RichTextField(blank=True, verbose_name='Содержимое')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тоо-Ашуу', max_length=120, verbose_name='Название')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное название')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Слоган')),
                ('season', models.CharField(blank=True, help_text='Например: Сезон 2026/2027', max_length=60, verbose_name='Сезон')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[600, 200], upload_to='site/', verbose_name='Логотип')),
                ('open_weekdays', models.CharField(blank=True, default='5,6', help_text='Дни, когда работают подъёмники', max_length=20, verbose_name='Рабочие дни')),
                ('lift_hours', models.CharField(blank=True, default='9:30 – 16:30', max_length=60, verbose_name='Часы работы подъёмников')),
                ('is_season_open', models.BooleanField(default=True, help_text='Снимите галочку в межсезонье — на сайте появится «Сезон закрыт»', verbose_name='Сезон открыт')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=30, verbose_name='Телефон 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_hours', models.TextField(blank=True, help_text='Каждая строка — отдельный пункт', verbose_name='Режим работы (текст)')),
                ('whatsapp', models.CharField(blank=True, help_text='Номер в любом формате', max_length=30, verbose_name='WhatsApp')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('map_embed_url', models.URLField(blank=True, help_text='Если пусто — карта строится по координатам', max_length=1000, verbose_name='Своя карта (iframe src)')),
                ('directions', apps.base.models.RichTextField(blank=True, verbose_name='Как добраться')),
                ('transfer_contact', models.CharField(blank=True, max_length=120, verbose_name='Трансфер: контактное лицо')),
                ('transfer_phone', models.CharField(blank=True, max_length=30, verbose_name='Трансфер: телефон')),
                ('altitude_base', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота: низ, м')),
                ('altitude_top', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота: верх, м')),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Расстояние от Бишкека, км')),
                ('about_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1600, 1200], upload_to='site/', verbose_name='Фото для блока «О курорте»')),
                ('temperature', models.SmallIntegerField(blank=True, null=True, verbose_name='Температура на склоне, °C')),
                ('snow_depth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота снега, см')),
                ('snow_note', models.CharField(blank=True, help_text='Например: свежий пухляк', max_length=120, verbose_name='Состояние снега')),
                ('conditions_updated_at', models.DateTimeField(auto_now=True, verbose_name='Условия обновлены')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
