# Generated by Django 5.2 on 2026-10-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='Baytur', max_length=120, verbose_name='Название'),
        ),
    ]
